# Documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
# Dependabot for pip can read the pyproject.toml at "/".
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

# This looks for new versions of actions.
  - package-ecosystem: "github-actions"
    directory: ".github/workflows/"
    schedule:
      interval: "weekly"