repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: python -m black
        require_serial: true
        language: system
        types: [python]
        stages: [pre-commit]
      - id: isort
        name: isort
        entry: python -m isort
        require_serial: true
        language: system
        types: [python]
        stages: [pre-commit]
      - id: autoflake
        name: autoflake
        entry: python -m autoflake --in-place --remove-all-unused-imports --remove-unused-variables
        require_serial: true
        language: system
        types: [python]
        stages: [pre-commit]
      - id: flake8
        name: flake8
        entry: python -m flake8 --count --show-source --statistics --verbose
        language: system
        pass_filenames: false
        fail_fast: true
        stages: [pre-push]
      - id: bandit
        name: bandit
        entry: python -m bandit -ll -f txt -c pyproject.toml -r .
        language: system
        pass_filenames: false
        fail_fast: true
        stages: [pre-push]
      - id: pytest
        name: pytest
        entry: python -m pytest
        language: system
        pass_filenames: false
        fail_fast: true
        stages: [pre-push]
