name: Build
on:
  workflow_dispatch:
  push:
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/build.yml'

env:
  PLAYWRIGHT_BROWSERS_PATH: 0

jobs:
  Build-macOS:
    if: ${{ github.ref_name == 'main' }}
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup environment
        run: |
          python -m pip install ".[dev]"
      - name: Install playwright browser backend
        run: |
          playwright install chromium
      - name: Build macOS binary
        run: |
          pyinstaller -y -F kion-auth.py
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: kion-auth-macos-${{ github.sha }}
          path: dist/kion-auth
          overwrite: true

  Build-Linux:
    if: ${{ github.ref_name == 'main' }}
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup environment
        run: |
          python -m pip install ".[dev]"
      - name: Install playwright browser backend
        run: |
          playwright install chromium
      - name: Build linux binary
        run: |
          pyinstaller -y -F kion-auth.py
      - name: Upload linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: kion-auth-linux-${{ github.sha }}
          path: dist/kion-auth
          overwrite: true

  Build-Windows:
    if: ${{ github.ref_name == 'main' }}
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup environment
        run: |
          python -m pip install ".[dev]"
      - name: Install playwright browser backend
        run: |
          playwright install chromium
      - name: Build windows binary
        run: |
          pyinstaller -y -F kion-auth.py
          ls -l dist/
      - name: Upload windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: kion-auth-windows-${{ github.sha }}
          path: dist/kion-auth.exe
          overwrite: true
