name: Build kion-auth executables
on:
  workflow_dispatch:

# Temporarily disable push dispatch
#  push:
#    branches:
#      - main

env:
  PLAYWRIGHT_BROWSERS_PATH: 0

jobs:
  Build-macOS:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup virtual environment
        run: |
          python -m venv --clear .venv
          python -m pip install ".[dev]"
      - name: Install playwright browser backend
        run: |
          source .venv/bin/activate
          playwright install chromium
      - name: Build macOS binary
        run: |
          source .venv/bin/activate
          pyinstaller -y -F kion-auth.py
      - name: Release macOS binary
        uses: softprops/action-gh-release@v2
        with:
          name: kion-auth-macos-${{ github.run_number }}
          files: dist/kion-auth

  Build-Linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup virtual environment
        run: |
          python -m venv --clear .venv
          python -m pip install ".[dev]"
      - name: Install playwright browser backend
        run: |
          source .venv/bin/activate
          playwright install chromium
      - name: Build linux binary
        run: |
          source .venv/bin/activate
          pyinstaller -y -F kion-auth.py
      - name: Release linux binary
        uses: softprops/action-gh-release@v2
        with:
          name: kion-auth-linux-${{ github.run_number }}
          files: dist/kion-auth

  Build-Windows:
    if: github.ref_type == 'tag'
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup virtual environment
        run: |
          python -m venv --clear .venv
          python -m pip install ".[dev]"
      - name: Install playwright browser backend
        run: |
          source .venv/bin/activate
          playwright install chromium
      - name: Build windows binary
        run: |
          source .venv/bin/activate
          pyinstaller -y -F kion-auth.py
      - name: Release windows binary
        uses: softprops/action-gh-release@v2
        with:
          name: kion-auth-windows-${{ github.run_number }}
          files: dist/kion-auth
