name: Check for unused imports and variables

on:
  pull_request:

jobs:
  Check-Unused:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install autoflake

      - name: Check for unused imports/variables with autoflake
        run: |
          autoflake --check-diff --quiet --remove-all-unused-imports --remove-unused-variables --recursive --exclude venv .
