name: Code Linting

on: pull_request

jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install flake8 flake8-bugbear Flake8-pyproject
      - name: Lint using flake8
        run: |
          flake8 . --count --show-source --statistics --verbose
