name: Release
on:
  push:
    tags:
      - v*


jobs:
  Release:
    name: Release kion-auth
    runs-on: ubuntu-latest
    steps:
      - name: Get build run id of this sha
        env:
          GH_TOKEN: ${{ secrets.GHA_CLI_PAT }}
        run: |
          shaRunId="$(gh api /repos/hmrd-forpeople/kion-auth/actions/workflows/build.yml/runs --method get -f head_sha=${{ github.sha }} --jq ".workflow_runs[0].id")"
          echo 'SHA_RUN_ID='$shaRunId >> $GITHUB_ENV
      - name: Download built binaries
        uses: actions/download-artifact@v4
        with:
          pattern: kion-auth-*-${{ github.sha }}
          repository: ${{ github.repository }}
          github-token: ${{ secrets.GHA_PAT }}
          run-id: ${{ env.SHA_RUN_ID }}
      - name: Make binaries executable
        run: |
          chmod +x kion-auth-*/*
      - name: Rename binaries
        run: |
          mv kion-auth-macos-${{ github.sha }}/kion-auth kion-auth-macos
          mv kion-auth-linux-${{ github.sha }}/kion-auth kion-auth-linux
          mv kion-auth-windows-${{ github.sha }}/kion-auth.exe kion-auth-windows.exe
      - name: Remove directories
        run: |
          rmdir kion-auth-macos-${{ github.sha }}
          rmdir kion-auth-linux-${{ github.sha }}
          rmdir kion-auth-windows-${{ github.sha }}
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GHA_RELEASE_PAT }}
          name: kion-auth-${{ github.ref_name }}
          files: |
            kion-auth-macos
            kion-auth-linux
            kion-auth-windows.exe
