name: Release kion-auth
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Sha to work on'
        required: true
        type: string
      runid:
        description: 'Run ID of successful build'
        required: true
        type: string

# Temporarily disable push dispatch
#  push:
#    branches:
#      - main

jobs:
  Release:
    # if: github.ref_type == 'tag'
    name: Release kion-auth
    runs-on: ubuntu-latest
    steps:
      - name: Starting ls check
        run: |
          ls -al
      - name: Download built binaries
        uses: actions/download-artifact@v4
        with:
          pattern: kion-auth-*-${{ inputs.ref }}
          repository: ${{ github.repository }}
          github-token: ${{ secrets.GHA_PAT }}
          run-id: ${{ inputs.runid }}
      - name: post-download ls check
        run: |
          ls -al
      - name: Make binaries executable
        run: |
          chmod +x kion-auth-*
      - name: post-chmod ls check
        run: |
          ls -al
      - name: Rename binaries
        run: |
          mv kion-auth-macos-${{ inputs.ref }} kion-auth-macos
          mv kion-auth-linux-${{ inputs.ref }} kion-auth-linux
          #mv kion-auth-windows-${{ inputs.ref }} kion-auth-windows
      - name: Final ls check
        run: |
          ls -al
      - name: Create release
        # Temporarily disable the actual release to see what happens
        if: github.repository == 'nwgh/homedir'
        uses: softprops/action-gh-release@v2
        with:
          name: kion-auth-${{ github.ref_name }}
          files: |
            kion-auth-macos
            kion-auth-linux
            # kion-auth-windows
