name: Security Scan

on: pull_request

jobs:
  Security-Scan:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install tomli bandit
      - name: Security scan using bandit
        run: |
          bandit -ll -f txt -c pyproject.toml -r .
